name: monster
main: cn.handyplus.monster.Monster
version: 3.0.6
author: handy
api-version: 1.13
website: https://ricedoc.handyplus.cn/wiki/monster/
description: 一个有点好用的怪物插件
commands:
  monster:
    description: 主命令